# Generated by Django 4.1.7 on 2023-05-23 22:43

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название товара')),
                ('price', models.CharField(max_length=255, null=True, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ('-id',),
            },
        ),
    ]
