# Generated by Django 4.1.7 on 2023-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/shop/icons', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
