# Generated by Django 4.1.7 on 2023-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_productlist_full_description_alter_category_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35, verbose_name='Пользователь')),
                ('product', models.CharField(max_length=255, verbose_name='Товар в коризну')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
            ],
        ),
    ]
